#line 2 "obj_scanner.cpp"

#line 4 "obj_scanner.cpp"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 37
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

    /* The c++ scanner is a mess. The FlexLexer.h header file relies on the
     * following macro. This is required in order to pass the c++-multiple-scanners
     * test in the regression suite. We get reports that it breaks inheritance.
     * We will address this in a future release of flex, or omit the C++ scanner
     * altogether.
     */
    #define yyFlexLexer yyFlexLexer

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */
#include <iostream> 
#include <errno.h>
#include <cstdlib>
#include <cstdio>
#include <cstring>
/* end standard C++ headers. */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex. 
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{

	std::istream* yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

#define yytext_ptr yytext

#include <FlexLexer.h>

int yyFlexLexer::yywrap() { return 1; }
int yyFlexLexer::yylex()
	{
	LexerError( "yyFlexLexer::yylex invoked but %option yyclass used" );
	return 0;
	}

#define YY_DECL int obj_scanner::yylex()

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 70
#define YY_END_OF_BUFFER 71
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[206] =
    {   0,
       61,   61,   71,   70,   61,   60,   70,   70,   67,   67,
       67,   69,   63,   68,   66,   66,   66,   66,   68,   66,
       66,   43,   66,   11,   22,   66,   66,   10,   66,   66,
       25,    9,   66,   23,   66,   66,    1,   61,    0,    0,
        0,   62,   67,   67,   63,   68,   67,   64,   64,   63,
       66,   37,   38,   40,   39,   58,   41,   56,   57,   59,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   24,   66,   66,   66,   53,
       66,   66,   66,   66,   19,   66,   66,   66,   66,    3,
        4,    2,   65,   64,   67,   67,   64,   66,   66,   66,

       66,   21,   66,   66,   66,   66,    6,   20,   66,   66,
       29,   66,   66,   66,   54,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   64,   67,    0,   67,   64,   66,
        7,   50,   66,   66,   66,   12,   66,   17,   66,   66,
       66,   66,   15,   55,   18,   66,   66,    8,   14,   66,
       16,   66,   52,   64,   26,   66,   66,   34,   13,   66,
       42,   66,   66,   66,   48,   66,   66,   66,   66,   35,
       66,   66,   66,    5,   66,   44,   45,   46,   47,   66,
       66,   31,   36,   66,   66,   30,   66,   66,   66,   66,
       66,   66,   27,   28,   49,   66,   66,   66,   66,   66,

       33,   66,   32,   51,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    1,    4,    5,    1,    1,    1,    1,    6,
        6,    1,    7,    1,    8,    9,   10,   11,   11,   12,
       11,   11,   11,   11,   11,   11,   11,   13,    1,    1,
        1,    1,    6,    1,   14,   15,   15,   16,   17,   15,
       15,   15,   15,   15,   18,   15,   15,   19,   15,   15,
       15,   15,   20,   21,   15,   15,   15,   15,   15,   15,
        1,   22,    1,    1,   23,    1,   24,   25,   26,   27,

       28,   29,   30,   31,   32,   33,   34,   35,   36,   37,
       38,   39,   15,   40,   41,   42,   43,   44,   45,   15,
       46,   15,    1,    1,    1,   13,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[47] =
    {   0,
        1,    1,    2,    1,    1,    3,    1,    4,    4,    1,
        4,    4,    5,    4,    4,    4,    4,    4,    4,    4,
        4,    5,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4
    } ;

static yyconst flex_int16_t yy_base[212] =
    {   0,
        0,    0,  105, 1280,   97, 1280,   90,   79,    0,   41,
       44, 1280,   78,    0,   52,   95,   40,   69,   77,   88,
      114,  120,   51,  122,  138,  140,  145,  147,  163,  168,
      170,  186,  188,  207,  194,  196,  216,   75,   69,   58,
       56, 1280,    0,   63,  251,    0,   89,  268,  291,  311,
      241,  243,  248,  259,  264,  271,  283,  290,  301, 1280,
      306,  313,  321,  331,  337,  342,  349,  358,  364,  373,
      380,  382,  391,  400,  406,  411,  416,  422,  431,  437,
      442,  447,  453,  462,  468,  473,  478,  480,  489,  496,
      498,  504,   47,  540,  112,  563,  580,  514,  536,  520,

      572,  560,  579,  588,  594,  599,  604,  606,  615,  622,
      627,  634,  642,  652,  654,  662,  672,  677,  682,  685,
      702,  708,  714,  720,  756,  521,   37,  752,  764,  755,
      761,  767,  773,  779,  785,  805,  795,  797,  803,  829,
      834,  841,  849,  857,  864,  869,  875,  884,  890,  895,
      900,  902,  108,   59,  910,  918,  925,  930,  936,  941,
      946,  974,  948,  956,  968,  979,  986,  995,  997, 1004,
     1016, 1023, 1025, 1032, 1043, 1048, 1050, 1058, 1066, 1068,
     1073, 1078, 1084, 1093, 1099, 1104, 1111, 1119, 1127, 1135,
     1129, 1147, 1153, 1155, 1162, 1173, 1182, 1171, 1189, 1191,

     1198, 1209, 1216, 1218, 1280, 1259, 1264, 1267, 1269, 1272,
     1274
    } ;

static yyconst flex_int16_t yy_def[212] =
    {   0,
      205,    1,  205,  205,  205,  205,  206,  207,  208,  209,
      209,  205,  210,  211,  210,  210,   16,   16,  211,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   21,   16,   16,   34,  205,  206,  205,
      207,  205,  208,  209,  209,  211,  209,  209,  209,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,  205,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,  205,  209,  209,  209,  209,   16,   16,   16,

       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   34,
       16,   16,   16,   16,  209,  209,  205,  209,  209,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,  209,  205,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,

       16,   16,   16,   16,    0,  205,  205,  205,  205,  205,
      205
    } ;

static yyconst flex_int16_t yy_nxt[1327] =
    {   0,
        4,    5,    6,    7,    8,    9,    4,   10,   11,   12,
       13,   13,   14,   15,   15,   15,   15,   16,   17,   15,
       18,   19,   15,   15,   20,   21,   22,   23,   24,   25,
       26,   27,   15,   15,   28,   29,   30,   31,   32,   33,
       34,   35,   36,   37,   15,   15,   43,  154,  154,   43,
       39,   45,   45,   46,   48,   48,   46,   43,   42,   44,
       44,   39,   46,   51,   46,   46,   51,   51,   43,  154,
      154,   56,   93,   46,   51,   46,   38,   51,   51,   60,
       57,   42,   47,   43,   46,   44,   49,   71,   50,   50,
       46,   51,   51,   40,   43,   51,   51,   58,   38,   46,

       43,   46,   44,   44,  205,  205,  205,   46,   59,   51,
       46,   51,  205,   43,   51,   61,   46,   43,   52,  205,
       46,   53,   54,   62,   46,  205,  205,  205,   51,   46,
       63,  205,  205,   46,   95,   55,   64,   51,  205,  205,
       51,   51,   69,   51,  205,   51,   51,   70,   51,   51,
      126,   65,  205,  205,   66,   67,   68,  205,  205,  205,
       51,   51,   51,   51,   51,   51,   51,   51,   51,  205,
       51,   51,   51,   51,   51,  205,  205,   72,   51,   73,
       51,  205,  205,  205,   74,   51,   75,   51,  205,   51,
       51,   51,   76,   51,   51,   78,   51,   51,   79,  205,

      205,  205,  205,   51,   77,  205,   80,  205,   51,   81,
       51,   51,   51,   51,   51,   82,  205,   51,  205,   51,
       51,   51,   51,   51,  205,  205,   51,  205,   51,   51,
      205,  205,   83,   88,   51,  205,   89,   84,  205,  205,
      205,   51,  205,  205,   51,   85,   51,   51,   86,   87,
      205,  205,   90,  205,   91,  205,   43,   92,   51,   94,
      205,   45,   45,   46,   51,  205,   51,   51,   51,   51,
       51,   51,   46,   43,   51,   51,  205,  205,   48,   48,
       46,   51,   51,   51,   96,   51,   51,   51,   51,   46,
       51,   51,  205,  205,   51,   96,   43,   51,   51,   51,

      205,   97,   97,   46,   51,  205,   51,   96,  205,   51,
       51,   51,   46,   51,  205,  205,   51,   51,   96,   49,
      205,   50,   50,   51,   51,  205,  205,   51,   51,   51,
       51,  205,   51,   51,   51,  205,   99,   51,   51,   51,
       51,   51,  205,  205,   51,  205,   51,   51,   51,   98,
      205,   51,  205,   51,   51,  205,  100,   51,   51,  205,
       51,   51,  101,   51,   51,   51,  205,  205,   51,   51,
      205,   51,   51,  102,  205,   51,  104,   51,  205,  205,
      205,   51,   51,  103,   51,   51,  205,   51,  205,   51,
       51,   51,  205,  205,  205,  106,   51,  105,   51,   51,

       51,  205,  107,   51,   51,   51,  108,   51,   51,   51,
      205,  205,  205,   51,   51,  205,  109,   51,   51,  205,
       51,  205,   51,   51,  205,  110,  111,   51,  205,   51,
      205,   51,   51,   51,   51,  205,  205,   51,   51,   51,
       51,  205,   51,   51,  112,   51,   51,  205,   51,   51,
      113,   51,  205,  205,   51,  205,   51,   51,   51,  115,
       51,  205,   51,   51,   51,   51,  114,  205,   51,   51,
       51,   51,  205,   51,   51,  117,   51,   51,  205,   51,
       51,  116,   51,  205,  205,  119,  205,   51,   51,   51,
      205,   51,  118,   51,   51,   51,   51,  205,  205,   51,

      120,   51,   51,  122,   51,   51,   51,   51,   51,  205,
      205,  123,   51,   51,  205,   51,  124,  121,   51,   51,
       51,   51,   51,   51,   51,   51,   43,   51,  205,   51,
       51,   51,  205,   46,  205,  205,   51,   51,   51,  205,
       51,  130,   46,   51,   51,   43,   51,   51,  153,  205,
      125,  125,   46,  205,   51,  205,   96,  205,  132,   51,
       51,   46,   51,   51,  205,  205,  205,   96,   43,  127,
      128,  205,  205,  129,  129,   46,   51,  131,  205,  205,
      205,  205,  205,   51,   46,   43,   51,   51,  205,  205,
       97,   97,   46,  205,  205,   51,   96,  205,   51,   51,

       51,   46,   51,  205,  205,   51,   51,   96,  133,  205,
      205,   51,   51,  135,   51,   51,  205,   51,  205,   51,
       51,   51,   51,  205,  134,   51,   51,   51,   51,   51,
       51,   51,   51,   51,   51,  137,  205,  136,   51,   51,
      205,   51,  138,  205,   51,   51,   51,  205,   51,   51,
       51,  205,  205,   51,   51,   51,  140,   51,  205,  205,
       51,   51,   51,  205,  139,   51,  205,   51,   51,   51,
      205,  205,  205,  205,   51,   51,  141,   51,   51,   51,
       51,   51,   51,  205,  205,   51,  205,  142,   51,   51,
      205,  205,   51,  205,   51,   51,  205,  143,   51,   51,

       51,  205,   51,   51,   51,   51,  144,  205,  146,   51,
      147,  205,   51,  205,  205,   51,  205,   51,  205,  205,
      145,  205,   51,  148,  205,   51,   51,   51,   51,   51,
      149,   51,  205,  150,   51,   51,  205,   51,  205,  205,
       51,   51,   51,   51,  205,  205,   51,   51,   51,  151,
      205,  205,  205,  205,   51,  152,  205,   43,  205,  205,
       51,   43,  129,  129,   46,  205,  125,  125,   46,   43,
      205,  205,   96,   46,  129,  129,   46,   46,   51,  205,
      205,   51,   51,   96,   51,   46,  205,   51,   51,  155,
       51,  205,  205,   51,   51,   51,   51,  205,  205,   51,

       51,   51,   51,  205,  205,   51,   51,   51,   51,  205,
      205,   51,   51,   51,  156,  158,  159,  157,   51,   51,
       51,   51,   51,   51,   51,   51,   51,  205,   51,   51,
       51,   51,   51,  205,  205,   51,  160,   51,  161,  205,
      205,  205,  205,   51,  205,   51,  162,  163,  205,  205,
      205,  205,   51,  164,  205,  165,   51,   51,  205,  205,
       51,   51,  162,  205,   51,  167,  166,   51,   51,   51,
      205,  205,   51,  205,   51,   51,   51,  205,  205,  205,
       51,   51,  168,   51,   51,  205,  205,   51,  205,   51,
       51,   51,   51,  205,  205,   51,   51,   51,   51,  205,

      205,   51,   51,  205,   51,  170,  169,   51,  205,   51,
       51,   51,  205,   51,  205,   51,   51,   51,   51,  205,
      205,   51,  171,   51,   51,   51,   51,   51,   51,   51,
       51,  205,  205,   51,  205,   51,   51,   51,  205,  205,
       51,   51,   51,  172,   51,  173,  205,  205,   51,  205,
       51,   51,  174,   51,  205,  205,   51,   51,   51,   51,
      205,  205,   51,   51,   51,   51,  205,   51,  175,   51,
       51,   51,   51,   51,   51,   51,   51,  205,  205,   51,
      205,   51,   51,   51,  205,  205,   51,  176,  179,  177,
      205,   51,  205,  178,   51,   51,   51,  176,  180,  205,

      177,   51,   51,  205,  205,   51,   51,  205,   51,   51,
      182,  205,   51,   51,  178,  205,  205,  181,   51,   51,
       51,   51,   51,   51,   51,  205,   51,   51,  205,  183,
       51,   51,  205,  205,  205,   51,  205,   51,  185,   51,
      205,  184,   51,   51,   51,  205,   51,  205,   51,   51,
       51,   51,   51,  205,  205,   51,   51,  186,   51,   51,
      205,  205,  205,   51,  187,   51,   51,  205,  205,   51,
       51,   51,   51,   51,   51,   51,   51,   51,  205,  205,
      205,   51,  188,   51,   51,   51,  205,  205,   51,   51,
       51,   51,   51,   51,   51,   51,  190,  205,   51,   51,

       51,   51,  205,  189,   51,   51,   51,   51,   51,  205,
       51,   51,  205,   51,  205,  191,   51,  205,   51,   51,
       51,  205,   51,  205,   51,   51,   51,   51,  205,  205,
       51,   51,  205,   51,   51,  205,  192,   51,   51,   51,
      205,  205,   51,  205,   51,   51,   51,  205,  205,  193,
       51,   51,   51,   51,   51,   51,   51,  194,   51,   51,
      196,   51,   51,  205,  205,  195,  197,   51,  205,   51,
       51,  198,  205,   51,   51,   51,   51,  205,   51,   51,
       51,   51,   51,  205,  205,   51,  205,   51,   51,   51,
      205,  205,  205,   51,   51,   51,   51,   51,   51,   51,

       51,  205,   51,  201,  199,   51,  200,  205,   51,   51,
      205,   51,   51,   51,   51,   51,   51,   51,   51,  205,
      205,   51,   51,  203,   51,   51,  205,  205,  205,   51,
      202,   51,   51,  205,  205,   51,   51,  205,   51,   51,
      205,   51,   51,   51,   51,   51,  205,  205,  205,   51,
      205,  205,  205,  205,  204,  205,   51,  205,   51,   39,
      205,   39,   39,   39,   41,   41,   41,   41,   41,   43,
       43,   44,   44,   44,   51,   51,   51,   46,   46,    3,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,

      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205
    } ;

static yyconst flex_int16_t yy_chk[1327] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   10,  127,  127,   11,
       93,   10,   10,   10,   11,   11,   11,   15,   41,   15,
       15,   40,   10,   17,   15,   11,   17,   17,   44,  154,
      154,   17,   39,   15,   23,   44,   38,   23,   23,   19,
       17,    8,   10,   13,   44,   13,   13,   23,   13,   13,
       13,   23,   18,    7,   47,   18,   18,   18,    5,   13,

       16,   47,   16,   16,    3,    0,    0,   16,   18,   18,
       47,   20,    0,  153,   20,   20,   16,   95,   16,    0,
      153,   16,   16,   20,   95,    0,    0,    0,   20,  153,
       20,    0,    0,   95,   47,   16,   21,   21,    0,    0,
       21,   21,   22,   22,    0,   24,   22,   22,   24,   24,
       95,   21,    0,    0,   21,   21,   21,    0,    0,    0,
       22,   25,   24,   26,   25,   25,   26,   26,   27,    0,
       28,   27,   27,   28,   28,    0,    0,   26,   25,   27,
       26,    0,    0,    0,   28,   27,   29,   28,    0,   29,
       29,   30,   29,   31,   30,   30,   31,   31,   31,    0,

        0,    0,    0,   29,   29,    0,   31,    0,   30,   32,
       31,   33,   32,   32,   33,   33,    0,   35,    0,   36,
       35,   35,   36,   36,    0,    0,   32,    0,   33,   34,
        0,    0,   34,   35,   35,    0,   36,   34,    0,    0,
        0,   37,    0,    0,   34,   34,   37,   34,   34,   34,
        0,    0,   37,    0,   37,    0,   45,   37,   37,   45,
        0,   45,   45,   45,   51,    0,   52,   51,   51,   52,
       52,   53,   45,   48,   53,   53,    0,    0,   48,   48,
       48,   51,   54,   52,   48,   54,   54,   55,   53,   48,
       55,   55,    0,    0,   56,   48,   49,   56,   56,   54,

        0,   49,   49,   49,   55,    0,   57,   49,    0,   57,
       57,   56,   49,   58,    0,    0,   58,   58,   49,   50,
        0,   50,   50,   57,   59,    0,    0,   59,   59,   61,
       58,    0,   61,   61,   50,    0,   62,   50,   50,   62,
       62,   59,    0,    0,   63,    0,   61,   63,   63,   61,
        0,   50,    0,   62,   64,    0,   63,   64,   64,    0,
       65,   63,   64,   65,   65,   66,    0,    0,   66,   66,
        0,   64,   67,   65,    0,   67,   67,   65,    0,    0,
        0,   68,   66,   66,   68,   68,    0,   69,    0,   67,
       69,   69,    0,    0,    0,   69,   70,   68,   68,   70,

       70,    0,   70,   71,   69,   72,   71,   71,   72,   72,
        0,    0,    0,   70,   73,    0,   72,   73,   73,    0,
       71,    0,   72,   74,    0,   73,   74,   74,    0,   75,
        0,   73,   75,   75,   76,    0,    0,   76,   76,   77,
       74,    0,   77,   77,   75,   78,   75,    0,   78,   78,
       77,   76,    0,    0,   79,    0,   77,   79,   79,   79,
       80,    0,   78,   80,   80,   81,   78,    0,   81,   81,
       82,   79,    0,   82,   82,   82,   83,   80,    0,   83,
       83,   81,   81,    0,    0,   84,    0,   82,   84,   84,
        0,   85,   83,   83,   85,   85,   86,    0,    0,   86,

       86,   87,   84,   88,   87,   87,   88,   88,   85,    0,
        0,   88,   89,   86,    0,   89,   89,   87,   87,   90,
       88,   91,   90,   90,   91,   91,  126,   92,    0,   89,
       92,   92,    0,  126,    0,    0,   90,   98,   91,    0,
       98,   98,  126,  100,   92,   94,  100,  100,  126,    0,
       94,   94,   94,    0,   98,    0,   94,    0,  100,   99,
      100,   94,   99,   99,    0,    0,    0,   94,   96,   96,
       96,    0,    0,   96,   96,   96,   99,   99,    0,    0,
        0,    0,    0,  102,   96,   97,  102,  102,    0,    0,
       97,   97,   97,    0,    0,  101,   97,    0,  101,  101,

      102,   97,  103,    0,    0,  103,  103,   97,  101,    0,
        0,  104,  101,  104,  104,  104,    0,  105,    0,  103,
      105,  105,  106,    0,  103,  106,  106,  107,  104,  108,
      107,  107,  108,  108,  105,  106,    0,  105,  109,  106,
        0,  109,  109,    0,  107,  110,  108,    0,  110,  110,
      111,    0,    0,  111,  111,  109,  112,  112,    0,    0,
      112,  112,  110,    0,  110,  113,    0,  111,  113,  113,
        0,    0,    0,    0,  112,  114,  113,  115,  114,  114,
      115,  115,  113,    0,    0,  116,    0,  114,  116,  116,
        0,    0,  114,    0,  115,  117,    0,  116,  117,  117,

      118,    0,  116,  118,  118,  119,  117,    0,  119,  119,
      120,    0,  117,    0,    0,  120,    0,  118,    0,    0,
      118,    0,  119,  120,    0,  121,  120,  120,  121,  121,
      121,  122,    0,  122,  122,  122,    0,  123,    0,    0,
      123,  123,  121,  124,    0,    0,  124,  124,  122,  123,
        0,    0,    0,    0,  123,  124,    0,  128,    0,    0,
      124,  125,  128,  128,  128,    0,  125,  125,  125,  129,
        0,    0,  125,  128,  129,  129,  129,  125,  130,    0,
        0,  130,  130,  125,  131,  129,    0,  131,  131,  130,
      132,    0,    0,  132,  132,  130,  133,    0,    0,  133,

      133,  131,  134,    0,    0,  134,  134,  132,  135,    0,
        0,  135,  135,  133,  133,  135,  136,  134,  137,  134,
      138,  137,  137,  138,  138,  135,  139,    0,  136,  139,
      139,  136,  136,    0,    0,  137,  137,  138,  139,    0,
        0,    0,    0,  139,    0,  136,  140,  140,    0,    0,
        0,    0,  140,  140,    0,  140,  140,  141,    0,    0,
      141,  141,  140,    0,  142,  141,  140,  142,  142,  140,
        0,    0,  143,    0,  141,  143,  143,    0,    0,    0,
      144,  142,  142,  144,  144,    0,    0,  145,    0,  143,
      145,  145,  146,    0,    0,  146,  146,  144,  147,    0,

        0,  147,  147,    0,  145,  147,  146,  148,    0,  146,
      148,  148,    0,  149,    0,  147,  149,  149,  150,    0,
        0,  150,  150,  151,  148,  152,  151,  151,  152,  152,
      149,    0,    0,  155,    0,  150,  155,  155,    0,    0,
      151,  156,  152,  152,  156,  156,    0,    0,  157,    0,
      155,  157,  157,  158,    0,    0,  158,  158,  156,  159,
        0,    0,  159,  159,  160,  157,    0,  160,  160,  161,
      158,  163,  161,  161,  163,  163,  159,    0,    0,  164,
        0,  160,  164,  164,    0,    0,  161,  162,  163,  162,
        0,  165,    0,  162,  165,  165,  164,  162,  164,    0,

      162,  162,  166,    0,    0,  166,  166,    0,  165,  167,
      167,    0,  167,  167,  162,    0,    0,  166,  168,  166,
      169,  168,  168,  169,  169,    0,  167,  170,    0,  168,
      170,  170,    0,    0,    0,  168,    0,  169,  171,  171,
        0,  169,  171,  171,  170,    0,  172,    0,  173,  172,
      172,  173,  173,    0,    0,  174,  171,  172,  174,  174,
        0,    0,    0,  172,  173,  173,  175,    0,    0,  175,
      175,  176,  174,  177,  176,  176,  177,  177,    0,    0,
        0,  178,  175,  175,  178,  178,    0,    0,  176,  179,
      177,  180,  179,  179,  180,  180,  181,    0,  178,  181,

      181,  182,    0,  180,  182,  182,  179,  183,  180,    0,
      183,  183,    0,  181,    0,  184,  184,    0,  182,  184,
      184,    0,  185,    0,  183,  185,  185,  186,    0,    0,
      186,  186,    0,  184,  187,    0,  185,  187,  187,  185,
        0,    0,  188,    0,  186,  188,  188,    0,    0,  187,
      189,  187,  191,  189,  189,  191,  191,  188,  190,  188,
      190,  190,  190,    0,    0,  189,  191,  189,    0,  191,
      192,  192,    0,  192,  192,  190,  193,    0,  194,  193,
      193,  194,  194,    0,    0,  195,    0,  192,  195,  195,
        0,    0,    0,  193,  198,  194,  196,  198,  198,  196,

      196,    0,  195,  198,  196,  197,  197,    0,  197,  197,
        0,  198,  199,  196,  200,  199,  199,  200,  200,    0,
        0,  201,  197,  200,  201,  201,    0,    0,    0,  199,
      199,  200,  202,    0,    0,  202,  202,    0,  201,  203,
        0,  204,  203,  203,  204,  204,    0,    0,    0,  202,
        0,    0,    0,    0,  202,    0,  203,    0,  204,  206,
        0,  206,  206,  206,  207,  207,  207,  207,  207,  208,
      208,  209,  209,  209,  210,  210,  210,  211,  211,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,

      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205,  205,  205,  205,  205,
      205,  205,  205,  205,  205,  205
    } ;

/* Table of booleans, true if rule could match eol. */
static yyconst flex_int32_t yy_rule_can_match_eol[71] =
    {   0,
0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 
    1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,     };

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
#line 1 "obj_scanner.l"
#line 2 "obj_scanner.l"
#include "obj_scanner.h"

#include <iostream>
#include <string>
#include <vector>

#define YY_NO_UNISTD_H 1
#line 806 "obj_scanner.cpp"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
#define ECHO LexerOutput( yytext, yyleng )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
\
	if ( (result = LexerInput( (char *) buf, max_size )) < 0 ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) LexerError( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1
#define YY_DECL int yyFlexLexer::yylex()
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 27 "obj_scanner.l"


#line 909 "obj_scanner.cpp"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = & std::cin;

		if ( ! yyout )
			yyout = & std::cout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 206 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 205 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			yy_size_t yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					   
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 29 "obj_scanner.l"
return(obj_parser::token::VERTEX);
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 30 "obj_scanner.l"
return(obj_parser::token::TEXTURE);
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 31 "obj_scanner.l"
return(obj_parser::token::NORMAL);
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 32 "obj_scanner.l"
return(obj_parser::token::SPACE_VERTEX);
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 33 "obj_scanner.l"
return(obj_parser::token::CURVE_SURFACE_TYPE);
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 34 "obj_scanner.l"
return(obj_parser::token::DEGREE);
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 35 "obj_scanner.l"
return(obj_parser::token::BASIS_MATRIX);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 36 "obj_scanner.l"
return(obj_parser::token::STEP_SIZE);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 37 "obj_scanner.l"
return(obj_parser::token::POINT);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 38 "obj_scanner.l"
return(obj_parser::token::LINE);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 39 "obj_scanner.l"
return(obj_parser::token::FACE);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 40 "obj_scanner.l"
return(obj_parser::token::CURVE);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 41 "obj_scanner.l"
return(obj_parser::token::CURVE_2D);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 42 "obj_scanner.l"
return(obj_parser::token::SURFACE);
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 43 "obj_scanner.l"
return(obj_parser::token::PARAMETER);
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 44 "obj_scanner.l"
return(obj_parser::token::OUTER_TRIMMING_LOOP);
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 45 "obj_scanner.l"
return(obj_parser::token::INNER_TRIMMING_LOOP);
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 46 "obj_scanner.l"
return(obj_parser::token::SPECIAL_CURVE);
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 47 "obj_scanner.l"
return(obj_parser::token::SPECIAL_POINT);
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 48 "obj_scanner.l"
return(obj_parser::token::END);
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 49 "obj_scanner.l"
return(obj_parser::token::CONNECT);
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 50 "obj_scanner.l"
return(obj_parser::token::GROUP_NAME);
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 51 "obj_scanner.l"
return(obj_parser::token::SMOOTHING_GROUP);
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 52 "obj_scanner.l"
return(obj_parser::token::MERGING_GROUP);
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 53 "obj_scanner.l"
return(obj_parser::token::OBJECT_NAME);
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 54 "obj_scanner.l"
return(obj_parser::token::BEVEL_INTERPOLATION);
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 55 "obj_scanner.l"
return(obj_parser::token::COLOR_INTERPOLATION);
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 56 "obj_scanner.l"
return(obj_parser::token::DISSOLVE_INTERPOLATION);
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 57 "obj_scanner.l"
return(obj_parser::token::LOD);
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 58 "obj_scanner.l"
return(obj_parser::token::MATERIAL_NAME);
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 59 "obj_scanner.l"
return(obj_parser::token::MATERIAL_LIBRARY);
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 60 "obj_scanner.l"
return(obj_parser::token::SHADOW_CASTING);
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 61 "obj_scanner.l"
return(obj_parser::token::RAY_TRACING);
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 62 "obj_scanner.l"
return(obj_parser::token::CURVE_APPROX_TECH);
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 63 "obj_scanner.l"
return(obj_parser::token::SURFACE_APPROX_TECH);
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 65 "obj_scanner.l"
return(obj_parser::token::NEWMTL);
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 66 "obj_scanner.l"
return(obj_parser::token::KA);
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 67 "obj_scanner.l"
return(obj_parser::token::KD);
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 68 "obj_scanner.l"
return(obj_parser::token::KS);
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 69 "obj_scanner.l"
return(obj_parser::token::KE);
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 70 "obj_scanner.l"
return(obj_parser::token::NS);
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 71 "obj_scanner.l"
return(obj_parser::token::ILLUM);
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 72 "obj_scanner.l"
return(obj_parser::token::D);
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 73 "obj_scanner.l"
return(obj_parser::token::MAP_KA);
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 74 "obj_scanner.l"
return(obj_parser::token::MAP_KD);
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 75 "obj_scanner.l"
return(obj_parser::token::MAP_KS);
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 76 "obj_scanner.l"
return(obj_parser::token::MAP_NS);
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 77 "obj_scanner.l"
return(obj_parser::token::MAP_D);
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 78 "obj_scanner.l"
return(obj_parser::token::MAP_BUMP);
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 79 "obj_scanner.l"
return(obj_parser::token::BUMP);
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 80 "obj_scanner.l"
return(obj_parser::token::MAP_OPACITY);
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 81 "obj_scanner.l"
return(obj_parser::token::TYPE);
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 82 "obj_scanner.l"
return(obj_parser::token::ON);
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 83 "obj_scanner.l"
return(obj_parser::token::OFF);
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 84 "obj_scanner.l"
return(obj_parser::token::REFL);
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 85 "obj_scanner.l"
return(obj_parser::token::TF);
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 86 "obj_scanner.l"
return(obj_parser::token::TR);
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 87 "obj_scanner.l"
return(obj_parser::token::NI);
	YY_BREAK
case 59:
/* rule 59 can match eol */
YY_RULE_SETUP
#line 90 "obj_scanner.l"
{ yyloc->lines(); }	
	YY_BREAK
case 60:
/* rule 60 can match eol */
YY_RULE_SETUP
#line 91 "obj_scanner.l"
{ yyloc->lines(); }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 92 "obj_scanner.l"

	YY_BREAK
case 62:
/* rule 62 can match eol */
YY_RULE_SETUP
#line 93 "obj_scanner.l"
{ yyloc->lines(); /*std::cout << yytext;*/ return(obj_parser::token::COMMENT); }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 94 "obj_scanner.l"
{ yylval->ival = atoi(yytext); return(obj_parser::token::INTEGER); }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 95 "obj_scanner.l"
{ yylval->fval = atof(yytext); return(obj_parser::token::FLOAT); }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 96 "obj_scanner.l"
{ yylval->sval = new std::string(yytext); _strings.push_back(yylval->sval); return(obj_parser::token::STRING); }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 97 "obj_scanner.l"
{ yylval->sval = new std::string(yytext); _strings.push_back(yylval->sval); return(obj_parser::token::IDENTIFIER); }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 98 "obj_scanner.l"
{ yylval->sval = new std::string(yytext); _strings.push_back(yylval->sval); return(obj_parser::token::FILENAME); }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 99 "obj_scanner.l"
{ yylval->sval = new std::string(yytext); _strings.push_back(yylval->sval); return(obj_parser::token::PATH); }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 101 "obj_scanner.l"
return(obj_parser::token::SLASH);
	YY_BREAK
/* "\\"			return(BACK_SLASH); */
case 70:
YY_RULE_SETUP
#line 104 "obj_scanner.l"
ECHO;
	YY_BREAK
#line 1352 "obj_scanner.cpp"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::yyFlexLexer( std::istream* arg_yyin, std::ostream* arg_yyout )
{
	yyin = arg_yyin;
	yyout = arg_yyout;
	yy_c_buf_p = 0;
	yy_init = 0;
	yy_start = 0;
	yy_flex_debug = 0;
	yylineno = 1;	// this will only get updated if %option yylineno

	yy_did_buffer_switch_on_eof = 0;

	yy_looking_for_trail_begin = 0;
	yy_more_flag = 0;
	yy_more_len = 0;
	yy_more_offset = yy_prev_more_offset = 0;

	yy_start_stack_ptr = yy_start_stack_depth = 0;
	yy_start_stack = NULL;

	yy_buffer_stack = 0;
	yy_buffer_stack_top = 0;
	yy_buffer_stack_max = 0;

	yy_state_buf = 0;

}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
yyFlexLexer::~yyFlexLexer()
{
	delete [] yy_state_buf;
	yyfree(yy_start_stack  );
	yy_delete_buffer( YY_CURRENT_BUFFER );
	yyfree(yy_buffer_stack  );
}

/* The contents of this function are C++ specific, so the () macro is not used.
 */
void yyFlexLexer::switch_streams( std::istream* new_in, std::ostream* new_out )
{
	if ( new_in )
		{
		yy_delete_buffer( YY_CURRENT_BUFFER );
		yy_switch_to_buffer( yy_create_buffer( new_in, YY_BUF_SIZE  ) );
		}

	if ( new_out )
		yyout = new_out;
}

#ifdef YY_INTERACTIVE
int yyFlexLexer::LexerInput( char* buf, int /* max_size */ )
#else
int yyFlexLexer::LexerInput( char* buf, int max_size )
#endif
{
	if ( yyin->eof() || yyin->fail() )
		return 0;

#ifdef YY_INTERACTIVE
	yyin->get( buf[0] );

	if ( yyin->eof() )
		return 0;

	if ( yyin->bad() )
		return -1;

	return 1;

#else
	(void) yyin->read( buf, max_size );

	if ( yyin->bad() )
		return -1;
	else
		return yyin->gcount();
#endif
}

void yyFlexLexer::LexerOutput( const char* buf, int size )
{
	(void) yyout->write( buf, size );
}

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
int yyFlexLexer::yy_get_next_buffer()
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    yy_state_type yyFlexLexer::yy_get_previous_state()
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 206 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    yy_state_type yyFlexLexer::yy_try_NUL_trans( yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 206 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 205);

		return yy_is_jam ? 0 : yy_current_state;
}

    void yyFlexLexer::yyunput( int c, register char* yy_bp)
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

    int yyFlexLexer::yyinput()
{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		   
    yylineno++;
;

	return c;
}

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyFlexLexer::yyrestart( std::istream* input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yyFlexLexer::yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

    void yyFlexLexer::yy_load_buffer_state()
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yyFlexLexer::yy_create_buffer( std::istream* file, int size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yyFlexLexer::yy_delete_buffer( YY_BUFFER_STATE b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    void yyFlexLexer::yy_init_buffer( YY_BUFFER_STATE b, std::istream* file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

	b->yy_is_interactive = 0;
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yyFlexLexer::yy_flush_buffer( YY_BUFFER_STATE b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yyFlexLexer::yypush_buffer_state (YY_BUFFER_STATE new_buffer)
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yyFlexLexer::yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
void yyFlexLexer::yyensure_buffer_stack(void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

    void yyFlexLexer::yy_push_state( int new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc(new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc((void *) (yy_start_stack),new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(new_state);
}

    void yyFlexLexer::yy_pop_state()
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    int yyFlexLexer::yy_top_state()
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

void yyFlexLexer::LexerError( yyconst char msg[] )
{
    	std::cerr << msg << std::endl;
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 104 "obj_scanner.l"








